include: package:surf_lint_rules/analysis_options.yaml

dart_code_metrics:
  rules:
    - member-ordering-extended:
        exclude:
          - lib/src/base_test_screen.dart

linter:
  rules:
    avoid_types_on_closure_parameters:
      exclude:
        - lib/src/steps/*